name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  workflow: write

jobs:
  ci:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install environment dependencies
        run: apt update && apt install build-essential libpq-dev -y

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: flake8 *.py

      - name: Run tests
        run: coverage run -m pytest --cov --cov-report json

      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
