name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install environment dependencies
        run: apt update && apt install build-essential libpq-dev -y

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: flake8 *.py

      - name: Run tests
        run: coverage run -m pytest

      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v2
